name: demon# Name of the Catalog Entry
description: | 
bla-bla-bla
  # Description of the Catalog Entry
version: 0.0.1# Version of the Catalog to be used
category: Databases# Category to be used for searching catalog entries
maintainer: Natalya# The maintainer of the catalog entry
license: GPL# The license
projectURL: https://github.com/Natalyas/333.git# A URL related to the catalog entry
